"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BookOpenCheck, ShieldAlert, UsersRound } from "lucide-react";
import { useAuth } from "@/components/AuthProvider";
import { getSupabaseClient, type AppRole, type Profile } from "@/lib/supabase";

export function AdminPanel() {
  const { loading, session, profile, refreshProfile } = useAuth(); const [users, setUsers] = useState<Profile[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { if (profile?.role !== "admin") return; const client = getSupabaseClient(); if (!client) return; client.from("profiles").select("id,email,role,created_at").order("created_at", { ascending: false }).then(({ data, error }) => { if (error) setMessage(error.message); else setUsers((data || []) as Profile[]); }); }, [profile?.role]);
  async function setRole(id: string, role: AppRole) { const client = getSupabaseClient(); if (!client) return; const { error } = await client.from("profiles").update({ role }).eq("id", id); if (error) { setMessage(error.message); return; } setUsers((old) => old.map((item) => item.id === id ? { ...item, role } : item)); if (id === profile?.id) await refreshProfile(); }
  if (loading) return <p>Đang xác thực quyền truy cập...</p>;
  if (!session) return <Gate title="Cần đăng nhập" detail="Đăng nhập bằng tài khoản quản trị để quản lý người học và nội dung." />;
  if (profile?.role !== "admin") return <Gate title="Khu vực quản trị" detail="Tài khoản này đang là người dùng. Admin đầu tiên cần được gán role trong Supabase SQL Editor." />;
  return <div className="mt-8"><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<UsersRound />} label="Tài khoản" value={String(users.length)} /><Stat icon={<BookOpenCheck />} label="Nội dung" value="Markdown" /><Stat icon={<ShieldAlert />} label="Quyền" value="RLS bảo vệ" /></div><section className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white dark:border-white/10 dark:bg-[#111520]"><div className="border-b border-slate-100 p-5 dark:border-white/10"><h2 className="font-black">Vai trò người dùng</h2><p className="mt-1 text-sm text-slate-500">Chỉ admin mới có thể đổi quyền. API key AI không xuất hiện ở đây.</p>{message && <p className="mt-2 text-sm text-rose-600">{message}</p>}</div><div className="divide-y divide-slate-100 dark:divide-white/10">{users.map((user) => <div key={user.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="font-bold">{user.email || "Email chưa có"}</p><p className="mt-1 text-xs text-slate-500">{new Date(user.created_at).toLocaleString("vi-VN")}</p></div><select value={user.role} onChange={(event) => void setRole(user.id, event.target.value as AppRole)} className="rounded-xl border border-slate-200 bg-transparent px-3 py-2 text-sm font-bold dark:border-white/15"><option value="user">Người dùng</option><option value="admin">Quản trị</option></select></div>)}{users.length === 0 && <p className="p-5 text-sm text-slate-500">Chưa lấy được danh sách người dùng.</p>}</div></section></div>;
}
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-[#111520]"><div className="text-orange-600">{icon}</div><p className="mt-3 text-2xl font-black">{value}</p><p className="text-sm text-slate-500">{label}</p></div>; }
function Gate({ title, detail }: { title: string; detail: string }) { return <div className="mt-8 rounded-3xl border border-dashed border-slate-300 p-8 text-center dark:border-white/15"><ShieldAlert className="mx-auto h-8 w-8 text-orange-500"/><h2 className="mt-3 text-xl font-black">{title}</h2><p className="mx-auto mt-2 max-w-lg text-sm text-slate-500">{detail}</p><Link href="/sign-in" className="mt-5 inline-flex rounded-xl bg-orange-600 px-4 py-2.5 font-bold text-white">Đi tới đăng nhập</Link></div>; }
