const lessons = [
  { id:"iam", title:"IAM: Bảo mật & phân quyền", domain:"Security", level:"Nền tảng", time:"45 phút", icon:"⌘", summary:"Hiểu identity, policy, role, least privilege và cách xử lý AccessDenied.", content:`<p>IAM trả lời ba câu hỏi trong mọi request AWS: <b>ai</b> đang gọi, họ muốn làm <b>action</b> nào, và trên <b>resource</b> nào.</p><div class="callout"><b>Quy tắc vàng:</b> workload chạy trên AWS dùng IAM role với temporary credentials; không hard-code access key vào code hoặc EC2.</div><h2>Danh tính cần phân biệt</h2><div class="table-wrap"><table><tr><th>Thành phần</th><th>Vai trò</th><th>Khi dùng</th></tr><tr><td>Root user</td><td>Chủ account, toàn quyền</td><td>Chỉ tác vụ hiếm gặp; luôn bật MFA</td></tr><tr><td>IAM user</td><td>Danh tính dài hạn trong account</td><td>Legacy/trường hợp đặc biệt</td></tr><tr><td>IAM group</td><td>Gom user cùng quyền</td><td>Quản lý theo team</td></tr><tr><td>IAM role</td><td>Bộ quyền tạm thời có thể assume</td><td>EC2, Lambda, SSO, cross-account</td></tr></table></div><h2>Logic policy</h2><p>Mọi request bắt đầu với <i>implicit deny</i>. Cần một Allow phù hợp để thành công; nhưng chỉ một <i>explicit Deny</i> phù hợp là request bị từ chối ngay.</p><div class="callout"><b>Scenario:</b> EC2 phải đọc file S3. Gắn role có <code>s3:GetObject</code> giới hạn vào bucket/prefix cần thiết. Không tạo IAM user access key trên EC2.</div><h2>Lab gợi ý</h2><ol><li>Tạo bucket private và upload <code>training/hello.txt</code>.</li><li>Tạo policy chỉ Allow <code>s3:GetObject</code> trên <code>training/*</code>.</li><li>Gắn policy vào một role hoặc kiểm tra bằng IAM Policy Simulator.</li><li>Thử đọc file trong prefix và thử đọc prefix khác.</li></ol>`, quiz:{q:"Policy A Allow s3:GetObject, policy B Deny cùng action/resource. Kết quả?",options:["Allow vì policy A xuất hiện trước","Deny vì explicit Deny luôn thắng","Allow nếu user là admin"],answer:1,why:"Explicit Deny luôn được ưu tiên, kể cả khi có policy Allow khác."}},
  { id:"vpc", title:"VPC: Mạng AWS từ gốc", domain:"Networking", level:"Nền tảng", time:"50 phút", icon:"⌁", summary:"Thiết kế public/private subnet, route, Internet Gateway, NAT và network security.", content:`<p>VPC là mạng ảo riêng trong AWS. Bạn chia dải IP thành subnet, đặt route và kiểm soát traffic bằng Security Group/NACL.</p><div class="callout"><b>Kiến trúc web phổ biến:</b> Internet → Internet Gateway → ALB ở public subnet → EC2/App ở private subnets → RDS ở private DB subnets.</div><h2>Public và private không do tên subnet quyết định</h2><p>Một subnet được gọi là <b>public</b> khi route table có route đến Internet Gateway. Resource muốn truy cập Internet trực tiếp vẫn cần public IPv4/EIP phù hợp. Private subnet không có direct route đến IGW.</p><h2>NAT Gateway</h2><p>App ở private subnet vẫn cần tải package hoặc gọi API public? Route traffic outbound qua NAT Gateway đặt trong public subnet. NAT cho outbound connection, không cho Internet chủ động mở connection vào private instance.</p><h2>Security Group và NACL</h2><div class="table-wrap"><table><tr><th></th><th>Security Group</th><th>NACL</th></tr><tr><td>Áp dụng tại</td><td>ENI/resource</td><td>Subnet</td></tr><tr><td>State</td><td>Stateful</td><td>Stateless</td></tr><tr><td>Rule</td><td>Chỉ allow</td><td>Allow và deny</td></tr></table></div><h2>Lab gợi ý</h2><ol><li>Vẽ VPC 2 AZ, mỗi AZ có public và private subnet.</li><li>Gắn IGW, NAT Gateway, route tables.</li><li>Chỉ ALB cho Internet access; EC2 security group chỉ nhận HTTP từ SG của ALB.</li></ol>`, quiz:{q:"EC2 private subnet cần tải cập nhật từ Internet, chọn gì?",options:["Internet Gateway trực tiếp vào private subnet","NAT Gateway ở public subnet + private route table","Public IP cho mọi EC2"],answer:1,why:"NAT Gateway hỗ trợ outbound Internet cho private subnet mà không mở inbound unsolicited traffic."}},
  { id:"ec2", title:"EC2: Compute có kiểm soát", domain:"Compute", level:"Nền tảng", time:"40 phút", icon:"▣", summary:"Chọn instance, AMI, EBS, security group và mô hình giá phù hợp.", content:`<p>Amazon EC2 là máy chủ ảo khi bạn cần kiểm soát OS, runtime hoặc network ở mức máy chủ.</p><h2>Thành phần</h2><ul><li><b>AMI:</b> template gồm OS/cấu hình để tạo instance.</li><li><b>Instance type:</b> CPU, memory, network; chọn theo workload.</li><li><b>Security Group:</b> virtual firewall stateful cho instance/ENI.</li><li><b>EBS:</b> persistent block storage, thường gắn với một AZ.</li></ul><h2>Chọn mô hình giá</h2><div class="table-wrap"><table><tr><th>Kiểu</th><th>Phù hợp</th></tr><tr><td>On-Demand</td><td>Ngắn hạn, khó dự báo</td></tr><tr><td>Savings Plans/Reserved</td><td>Tải ổn định, cam kết sử dụng</td></tr><tr><td>Spot</td><td>Chịu gián đoạn: batch, CI, render</td></tr></table></div><div class="callout"><b>Production web:</b> đặt EC2 trong Auto Scaling Group trải hai AZ sau ALB. Đừng xem một EC2 là kiến trúc HA.</div><h2>Lab gợi ý</h2><ol><li>Launch một EC2 t2/t3 micro trong sandbox.</li><li>Chỉ mở SSH từ IP của bạn (hoặc dùng SSM Session Manager).</li><li>Gắn IAM role read-only S3; thử dùng AWS CLI/SDK không có access key.</li><li>Terminate instance và kiểm tra DeleteOnTermination của EBS.</li></ol>`, quiz:{q:"Web tier cần tự phục hồi instance lỗi và scale theo traffic?",options:["Một EC2 lớn hơn","ALB + Auto Scaling Group đa AZ","Chỉ thêm EBS volume"],answer:1,why:"ALB phân phối traffic; ASG thay thế instance lỗi và điều chỉnh số lượng instance."}},
  { id:"s3", title:"S3: Object storage bền vững", domain:"Storage", level:"Nền tảng", time:"45 phút", icon:"◫", summary:"Lưu object, bảo mật bucket, versioning, lifecycle và dùng cùng CloudFront.", content:`<p>S3 là object storage cho static assets, backup, logs và data lake. Nó không phải POSIX file system và không thay thế EBS/EFS.</p><h2>Ba lớp bảo vệ nên nhớ</h2><ol><li><b>Block Public Access:</b> để bật mặc định cho account/bucket.</li><li><b>Policy:</b> IAM identity policy và bucket policy cấp quyền có scope.</li><li><b>Encryption:</b> SSE-S3 hoặc SSE-KMS tùy yêu cầu kiểm soát key/audit.</li></ol><h2>Versioning và Lifecycle</h2><p>Versioning giữ các phiên bản object để khôi phục sau ghi đè/xóa nhầm. Nó có thể tăng chi phí; dùng Lifecycle để chuyển dữ liệu cũ đến tier rẻ hơn hoặc hết hạn noncurrent versions.</p><div class="callout"><b>Static website an toàn:</b> giữ bucket private, dùng CloudFront làm CDN và Origin Access Control (OAC) để CloudFront đọc S3. Không mở public bucket nếu không cần thiết.</div><h2>Lab gợi ý</h2><ol><li>Tạo bucket private, bật Versioning.</li><li>Upload/ghi đè một file và khôi phục version cũ.</li><li>Tạo Lifecycle rule cho noncurrent version test.</li><li>Cấu hình CloudFront + OAC cho content public.</li></ol>`, quiz:{q:"Nhiều EC2 cần dùng chung thư mục upload theo kiểu file system Linux. Chọn gì?",options:["S3","EBS gắn lần lượt vào từng EC2","EFS"],answer:2,why:"EFS là NFS file system elastic có thể được nhiều compute instance mount; S3 là object storage."}}
];

const storageKey = "aws-learning-progress";
let progress = JSON.parse(localStorage.getItem(storageKey) || "{}");
const config = window.AWS_LEARNING_CONFIG || {};
const supabaseClient = config.supabaseUrl && config.supabasePublishableKey && window.supabase ? window.supabase.createClient(config.supabaseUrl, config.supabasePublishableKey) : null;
let user = null;
const $ = s => document.querySelector(s);
const app = $("#app");
const title = $("#page-title");
const pct = () => Math.round(Object.keys(progress).length / lessons.length * 100);
function save(){localStorage.setItem(storageKey,JSON.stringify(progress));}
function card(l){const done=progress[l.id];return `<article class="lesson-card" data-lesson="${l.id}"><div class="lesson-top"><span class="service-icon">${l.icon}</span><span class="tag ${done?'done':''}">${done?'Đã hoàn thành':l.level}</span></div><h3>${l.title}</h3><p>${l.summary}</p><span class="tag">${l.domain} · ${l.time}</span></article>`}
function home(){title.textContent="Tổng quan";app.innerHTML=`<section class="hero"><div><div class="eyebrow">WELCOME BACK</div><h1>Học AWS có hệ thống.</h1><p class="subhead">Từ khái niệm đến kiến trúc thực tế — mỗi bài đều có scenario, lab và quiz.</p></div><div class="progress-summary"><div class="progress-row"><b>Tiến độ học</b><span>${pct()}%</span></div><div class="progress"><span style="width:${pct()}%"></span></div><p class="muted">${Object.keys(progress).length}/${lessons.length} bài đã hoàn thành</p></div></section><section class="stats"><article class="stat"><strong>${lessons.length}</strong><span>Bài nền tảng</span></article><article class="stat"><strong>${Object.keys(progress).length}</strong><span>Đã hoàn thành</span></article><article class="stat"><strong>4</strong><span>Domains AWS</span></article></section><div class="section-heading"><div><h2>Tiếp tục học</h2><p class="muted">Các bài nền tảng cần nắm trước khi làm architecture scenario.</p></div><button class="text-link" data-view="learn">Xem tất cả →</button></div><section class="course-grid">${lessons.map(card).join("")}</section>`; bindLessonCards();}
function learn(){title.textContent="Bài học";app.innerHTML=`<div class="eyebrow">COURSE LIBRARY</div><h1>Chọn một bài để bắt đầu</h1><p class="subhead">Bài học được viết từ gốc, sau đó cô đọng thành scenario và quiz để ôn thi.</p><section class="course-grid">${lessons.map(card).join("")}</section>`;bindLessonCards();}
function lesson(id){const l=lessons.find(x=>x.id===id);title.textContent=l.title;app.innerHTML=`<button class="text-link" data-view="learn">← Quay lại bài học</button><div class="lesson-layout"><article class="lesson-body"><div class="eyebrow">${l.domain.toUpperCase()} · ${l.time.toUpperCase()}</div><h1>${l.title}</h1><p class="subhead">${l.summary}</p>${l.content}<section class="question-card panel"><div class="eyebrow">KIỂM TRA NHANH</div><h2>${l.quiz.q}</h2><div class="quiz-options">${l.quiz.options.map((o,i)=>`<button class="quiz-option" data-answer="${i}">${String.fromCharCode(65+i)}. ${o}</button>`).join("")}</div><p class="result" id="result"></p></section></article><aside class="lesson-side panel"><b>Tiến độ bài học</b><p class="muted">Đánh dấu khi bạn đã đọc và tự trả lời quiz.</p><button class="primary-button" id="complete">${progress[id]?"✓ Đã hoàn thành":"Đánh dấu hoàn thành"}</button><button class="secondary-button" data-view="review">Ôn flashcards</button></aside></div>`;$("#complete").onclick=()=>{progress[id]=true;save();syncProgress(id);lesson(id)};document.querySelectorAll(".quiz-option").forEach(btn=>btn.onclick=()=>{const chosen=+btn.dataset.answer, ok=chosen===l.quiz.answer;document.querySelectorAll(".quiz-option").forEach(x=>x.disabled=true);btn.classList.add(ok?"correct":"wrong");document.querySelectorAll(".quiz-option")[l.quiz.answer].classList.add("correct");$("#result").textContent=(ok?"Chính xác. ":"Chưa đúng. ")+l.quiz.why;});bindViews();}
function review(){title.textContent="Ôn tập";const l=lessons[Math.floor(Math.random()*lessons.length)];app.innerHTML=`<div class="eyebrow">SPACED REVIEW</div><h1>Ôn nhanh hôm nay</h1><p class="subhead">Hãy tự trả lời trước khi xem đáp án.</p><section class="panel"><span class="tag">${l.domain}</span><h2 style="margin-top:16px">${l.quiz.q}</h2><button id="reveal" class="secondary-button">Hiện đáp án</button><p id="review-answer" class="callout" hidden><b>${l.quiz.options[l.quiz.answer]}</b><br>${l.quiz.why}</p></section><div class="section-heading"><h2>Tất cả bài học</h2></div><section class="course-grid">${lessons.map(card).join("")}</section>`;$("#reveal").onclick=()=>{$("#review-answer").hidden=false};bindLessonCards();}
function bindViews(){document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>navigate(b.dataset.view));}
function bindLessonCards(){document.querySelectorAll("[data-lesson]").forEach(c=>c.onclick=()=>lesson(c.dataset.lesson));bindViews();}
function navigate(view){document.querySelectorAll(".nav-link").forEach(x=>x.classList.toggle("active",x.dataset.view===view));({home,learn,review})[view]();}
async function syncProgress(lessonId){if(!user||!supabaseClient)return;await supabaseClient.from("lesson_progress").upsert({user_id:user.id,lesson_id:lessonId,completed_at:new Date().toISOString()},{onConflict:"user_id,lesson_id"});}
async function setupAuth(){if(!supabaseClient)return;const {data:{session}}=await supabaseClient.auth.getSession();user=session?.user||null;$("#auth-button").textContent=user?"Đã đồng bộ ✓":"Đăng nhập để đồng bộ";if(user){const {data}=await supabaseClient.from("lesson_progress").select("lesson_id").eq("user_id",user.id);data?.forEach(x=>progress[x.lesson_id]=true);save();home();}}
$("#auth-button").onclick=()=>{if(user){supabaseClient.auth.signOut();user=null;$("#auth-button").textContent="Đăng nhập để đồng bộ";return}$("#auth-dialog").showModal()};$("#send-link").onclick=async e=>{e.preventDefault();if(!supabaseClient){$("#auth-message").textContent="Chưa cấu hình Supabase.";return}const {error}=await supabaseClient.auth.signInWithOtp({email:$("#email").value,options:{emailRedirectTo:location.href}});$("#auth-message").textContent=error?error.message:"Đã gửi magic link. Kiểm tra email của bạn."};$("#theme-toggle").onclick=()=>document.body.classList.toggle("dark");document.querySelectorAll(".nav-link").forEach(b=>b.onclick=()=>navigate(b.dataset.view));$(".mobile-menu").onclick=()=>alert("Dùng các nút điều hướng trên đầu trang hoặc xoay màn hình rộng hơn để xem sidebar.");setupAuth();home();
